version: '3.7'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    container_name: elas

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    container_name: logs

  rating:
    build:
     context: services/ratings-data-service/
    ports:
       - "8083:8083"
    networks:
       - elk
    container_name: rati
  
  info:
    build:
     context: services/movie-info-service/
    ports:
       - "8082:8082"
    networks: 
       - elk
    container_name: info
  
  catalog:
    build: 
     context: services/movie-catalog-service/
    ports:
       - "8081:8081"
    depends_on: 
       - rating
       - info
    networks:
       - elk
    container_name: cata

  filebeat:
    build: 
      context: filebeat/
    user: 
      root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
        - rating
        - info
        - catalog
        - logstash
    networks:
      - elk
    container_name: beat

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    container_name: kiba

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
